### ISSUE TITLE
I do not find .py files

### ISSUE THREAD

**Issue by wenweixu** [jeonghwan723/DL_ENSO#3]
Hi, Jeong, I do not seem to find the .py files, for example this one: nino34.train_cmip.py. Are you going to share them? Or Did I miss it? Thank you

**Comment by JingliangGao** [comment]
@wenweixu Hi, when you run the comand like **csh nino34.cmip.csh**, it will copy a modified file named nino34.train_cmip.sample to your src folder（pwd ： **$HOME/DL_ENSO/CNN/output/nino34_2mothth_1/src**）. May this is what you need.

**Comment by wenweixu** [comment]
Got it, thanks.
